---
curso_info:
  uea: Reconocimiento de Patrones
  trimestre: 23-P
  aula_virtual: pass
...

---
calendario:
  uam_offset: 31
  inicio: 2023.08.07
  fin: 2023.10.25
  sesiones:
    teoría:
      - martes
    laboratorio:
      - jueves
  lugar:
    teoría: CP15
    laboratorio: CP15
  eventos:
    feriado:
      - 2023.09.15
      - 2023.09.16
      - 2023.10.12
...

---
query:
  exclude:
    temario:
      - asimilado en propuesta
      - obsoleto
      - mov ip
...

---
profe_info:
  nombre: Omar Piña Ramírez
  email: opina.ramirez@izt.uam.mx
...

---
dbs:
  main: 
    path: '/home/omarpr/Dropbox/Brain/Cursos/PR/dbs/planeacion.ods'
    tables:
      planeacion: temario
  traducción:
    días:
      Monday: lunes
      Tuesday: martes
      Wednesday: miércoles
      Thursday: jueves
      Friday: viernes
      Saturday: sábado
      Sunday: domigo
    meses:
      January: enero
      February: febrero
      March: marzo
      April: abril
      May: mayo
      June: junio
      July: julio
      August: agosto
      September: septiembre
      October: octubre
      November: noviembre
      December: diciembre
  evaluacion: 
    path: '/home/omarpr/Dropbox/Brain/Cursos/FAyD/db/curso.ods'
    tables:
      estudiantes: students
      evaluacion: evaluation
      ponderaciones: weight_items
...
